name: Generate CHANGELOG.md
on:
  push:
    branches:
      - dev#v2
  release:
    types: [published]
    
jobs:
  test:
    name: Generate CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - name: Checkout mitre-saf
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install github_changelog_generator
        run: |
          gem install github_changelog_generator
      - name: Run github_changelog_generator
        run: |
          git pull origin dev#v2
          export CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          github_changelog_generator -u mitre -p mitre-saf
      - name: Commit and push changes to CHANGELOG.md
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "dev#v2"
          commit-message: "Publish changelog"
          force-add: "true"
        env:
          CI: true
